### ISSUE TITLE
cannot import name Resource

### ISSUE THREAD

**Issue by Guoozz** [tabalinas/jsgrid-django#1]
I have installed simple_rest,but it doesn't work.
ps:My python version is 2.7.11+,django version 1.9.7

**Comment by tabalinas** [comment]
What do you mean by 'does not work'? Do you get an exception or nothing happens?
Have you tried to find a solution for simple_rest in particular, or you think it's related to js-grid?

**Comment by B3PS** [comment]
I have run into the same issue. 
The error is: "ImportError: cannot import name 'Resource'
Pycharm's auto-complete also does not suggest Resource. 

EDIT: I'm a derp, the module is django-simple-rest, not simple-rest

**Comment by tabalinas** [comment]
@CaseyMcGinnis, do you still have the issue? or you finally fixed it?

**Comment by B3PS** [comment]
@tabalinas thank you for your response. I resolved my issue. Thanks for the assistance (and excellent tool).
